@startuml

class GoodDayViewFXML{
  @FXML
}

class GoodDayViewController{
  +setUserSetting()
  +getUserSetting()
  +getCityData()
  +getWeatherInformation()
  +getActivities()
  +getActivityDetail()
  +getItems()
}
class GoodDayModel{
  -userData Array
  -itemData Array
  -activitiesData Array
  +GoodDayModel() // Prepare sample data
  +saveUserData()
  +getData()
  +openWeatherMap()
  +googleMapApi()
}
GoodDayViewFXML -- GoodDayViewController
GoodDayViewController -- GoodDayModel

@enduml