@startuml

class Main{
    -static Main instance
    -Stage stage
    +main()
    +start()
    +sendRegisterLocationPage()
    +sendWeatherInformationPage()
    -replaceSceneContent
    +static Main getInstance() return instance

}

class RegisterLocationPageView{
  FXML
}

class WeatherInformationPageView{
  FXML
}

class RegisterLocationPageController{
  +RegisterLocationPageController()
  +setUserSetting()
  +getUserSetting()
  +getCityData()
}

class WeatherInformationPageController{
  +WeatherInformationPageController()
  +setUserSetting()
  +getUserSetting()
  +getCityData()
  +getWeatherInformation()
  +getActivities()
  +getActivityDetail()
  +getItems()
}

class GoodDayModel{
  -userData Array
  -itemData Array
  -activitiesData Array
  +GoodDayModel() // Prepare sample data
  +saveUserData()
  +getData()
  +openWeatherMap()
  +googleMapApi()
}

Main -- RegisterLocationPageView
Main -- WeatherInformationPageView
RegisterLocationPageView -- RegisterLocationPageController
WeatherInformationPageView -- WeatherInformationPageController
RegisterLocationPageController -- GoodDayModel
WeatherInformationPageController -- GoodDayModel

@enduml