@startuml

class GoodDayViewFXML{
  @FXML
}

class GoodDayViewController{
  +setUserSetting()
  +getUserSetting()
  +getCityData()
  +setWeatherInformationToScreen()
  +setContentsToScreen()
}
class GoodDayModel{
  -itemList Array
  -activitiesList Array
  -activitiesData Array
  +GoodDayModel() // Prepare sample data
  +searchData()
  -getDataType()
  +saveUserSetting()
  +getUserSetting()
  +connectOpenWeatherMapApi()
}
GoodDayViewFXML -- GoodDayViewController
GoodDayViewController -- GoodDayModel

@enduml