@startuml

actor User
actor OpenWeatherMapAPI

left to right direction

rectangle GoodDay{
    User -> (Get weather information)
    User -> (Get sport activities)
    User -> (Get accessories)
    OpenWeatherMapAPI -left-> (Set weather information)
}

@enduml